name: Build README
on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        # necessary for github-action-til-autoformat-readme
        fetch-depth: 2
    - name: Autoformat README
      uses: cflynn07/github-action-til-autoformat-readme@1.2.0
      with:
        description: |
          스터디룸에 온 걸 환영합니다.
        list_most_recent: 4 # optional, lists most recent TILS below description
        date_format: "2020/01/01" # optional, must align to https://golang.org/pkg/time/#Time.Format
